package hibernate;
// Generated 2019-05-10 10:26:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Klasa generated by hbm2java
 */
public class Klasa  implements java.io.Serializable {


     private int idKlasy;
     private Nauczyciele nauczyciele;
     private String oddzial;
     private String rocznik;
     private Set klasaUczniowies = new HashSet(0);

    public Klasa() {
    }

	
    public Klasa(int idKlasy, Nauczyciele nauczyciele, String oddzial, String rocznik) {
        this.idKlasy = idKlasy;
        this.nauczyciele = nauczyciele;
        this.oddzial = oddzial;
        this.rocznik = rocznik;
    }
    public Klasa(int idKlasy, Nauczyciele nauczyciele, String oddzial, String rocznik, Set klasaUczniowies) {
       this.idKlasy = idKlasy;
       this.nauczyciele = nauczyciele;
       this.oddzial = oddzial;
       this.rocznik = rocznik;
       this.klasaUczniowies = klasaUczniowies;
    }
   
    public int getIdKlasy() {
        return this.idKlasy;
    }
    
    public void setIdKlasy(int idKlasy) {
        this.idKlasy = idKlasy;
    }
    public Nauczyciele getNauczyciele() {
        return this.nauczyciele;
    }
    
    public void setNauczyciele(Nauczyciele nauczyciele) {
        this.nauczyciele = nauczyciele;
    }
    public String getOddzial() {
        return this.oddzial;
    }
    
    public void setOddzial(String oddzial) {
        this.oddzial = oddzial;
    }
    public String getRocznik() {
        return this.rocznik;
    }
    
    public void setRocznik(String rocznik) {
        this.rocznik = rocznik;
    }
    public Set getKlasaUczniowies() {
        return this.klasaUczniowies;
    }
    
    public void setKlasaUczniowies(Set klasaUczniowies) {
        this.klasaUczniowies = klasaUczniowies;
    }

public String ComboKlasa(){
    
    StringBuilder combo = new StringBuilder();
    combo.append(rocznik);
    combo.append(" ");
    
    return combo.toString();
    
}


}


