package hibernate;
// Generated 2019-05-05 21:53:12 by Hibernate Tools 4.3.1



/**
 * KlasaUczniowieId generated by hbm2java
 */
public class KlasaUczniowieId  implements java.io.Serializable {


     private int idKlasy;
     private int idUcznia;

    public KlasaUczniowieId() {
    }

    public KlasaUczniowieId(int idKlasy, int idUcznia) {
       this.idKlasy = idKlasy;
       this.idUcznia = idUcznia;
    }
   
    public int getIdKlasy() {
        return this.idKlasy;
    }
    
    public void setIdKlasy(int idKlasy) {
        this.idKlasy = idKlasy;
    }
    public int getIdUcznia() {
        return this.idUcznia;
    }
    
    public void setIdUcznia(int idUcznia) {
        this.idUcznia = idUcznia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KlasaUczniowieId) ) return false;
		 KlasaUczniowieId castOther = ( KlasaUczniowieId ) other; 
         
		 return (this.getIdKlasy()==castOther.getIdKlasy())
 && (this.getIdUcznia()==castOther.getIdUcznia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdKlasy();
         result = 37 * result + this.getIdUcznia();
         return result;
   }   


}


