package hibernate;
// Generated 2019-05-17 14:24:19 by Hibernate Tools 4.3.1



/**
 * NauczycielePrzedmioty generated by hbm2java
 */
public class NauczycielePrzedmioty  implements java.io.Serializable {


     private NauczycielePrzedmiotyId id;
     private Nauczyciele nauczyciele;
     private Przedmioty przedmioty;

    public NauczycielePrzedmioty() {
    }

    public NauczycielePrzedmioty(NauczycielePrzedmiotyId id, Nauczyciele nauczyciele, Przedmioty przedmioty) {
       this.id = id;
       this.nauczyciele = nauczyciele;
       this.przedmioty = przedmioty;
    }
   
    public NauczycielePrzedmiotyId getId() {
        return this.id;
    }
    
    public void setId(NauczycielePrzedmiotyId id) {
        this.id = id;
    }
    public Nauczyciele getNauczyciele() {
        return this.nauczyciele;
    }
    
    public void setNauczyciele(Nauczyciele nauczyciele) {
        this.nauczyciele = nauczyciele;
    }
    public Przedmioty getPrzedmioty() {
        return this.przedmioty;
    }
    
    public void setPrzedmioty(Przedmioty przedmioty) {
        this.przedmioty = przedmioty;
    }




}


