package hibernate;
// Generated 2019-05-17 14:24:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Oceny generated by hbm2java
 */
public class Oceny  implements java.io.Serializable {


     private int idOceny;
     private Nauczyciele nauczyciele;
     private Przedmioty przedmioty;
     private Uczniowie uczniowie;
     private String opis;
     private Date dataWpisania;
     private int wartosc;

    public Oceny() {
    }

    public Oceny(int idOceny, Nauczyciele nauczyciele, Przedmioty przedmioty, Uczniowie uczniowie, String opis, Date dataWpisania, int wartosc) {
       this.idOceny = idOceny;
       this.nauczyciele = nauczyciele;
       this.przedmioty = przedmioty;
       this.uczniowie = uczniowie;
       this.opis = opis;
       this.dataWpisania = dataWpisania;
       this.wartosc = wartosc;
    }
   
    public int getIdOceny() {
        return this.idOceny;
    }
    
    public void setIdOceny(int idOceny) {
        this.idOceny = idOceny;
    }
    public Nauczyciele getNauczyciele() {
        return this.nauczyciele;
    }
    
    public void setNauczyciele(Nauczyciele nauczyciele) {
        this.nauczyciele = nauczyciele;
    }
    public Przedmioty getPrzedmioty() {
        return this.przedmioty;
    }
    
    public void setPrzedmioty(Przedmioty przedmioty) {
        this.przedmioty = przedmioty;
    }
    public Uczniowie getUczniowie() {
        return this.uczniowie;
    }
    
    public void setUczniowie(Uczniowie uczniowie) {
        this.uczniowie = uczniowie;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public Date getDataWpisania() {
        return this.dataWpisania;
    }
    
    public void setDataWpisania(Date dataWpisania) {
        this.dataWpisania = dataWpisania;
    }
    public int getWartosc() {
        return this.wartosc;
    }
    
    public void setWartosc(int wartosc) {
        this.wartosc = wartosc;
    }




}


