package hibernate;
// Generated 2019-03-31 21:14:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Przedmioty generated by hbm2java
 */
public class Przedmioty  implements java.io.Serializable {


     private int idPrzedmioty;
     private String nazwaPrzedmiotu;
     private Set ocenies = new HashSet(0);

    public Przedmioty() {
    }

	
    public Przedmioty(int idPrzedmioty, String nazwaPrzedmiotu) {
        this.idPrzedmioty = idPrzedmioty;
        this.nazwaPrzedmiotu = nazwaPrzedmiotu;
    }
    public Przedmioty(int idPrzedmioty, String nazwaPrzedmiotu, Set ocenies) {
       this.idPrzedmioty = idPrzedmioty;
       this.nazwaPrzedmiotu = nazwaPrzedmiotu;
       this.ocenies = ocenies;
    }
   
    public int getIdPrzedmioty() {
        return this.idPrzedmioty;
    }
    
    public void setIdPrzedmioty(int idPrzedmioty) {
        this.idPrzedmioty = idPrzedmioty;
    }
    public String getNazwaPrzedmiotu() {
        return this.nazwaPrzedmiotu;
    }
    
    public void setNazwaPrzedmiotu(String nazwaPrzedmiotu) {
        this.nazwaPrzedmiotu = nazwaPrzedmiotu;
    }
    public Set getOcenies() {
        return this.ocenies;
    }
    
    public void setOcenies(Set ocenies) {
        this.ocenies = ocenies;
    }




}


