package hibernate;
// Generated 2019-05-10 10:26:17 by Hibernate Tools 4.3.1



/**
 * UczniowiePrzedmioty generated by hbm2java
 */
public class UczniowiePrzedmioty  implements java.io.Serializable {


     private UczniowiePrzedmiotyId id;
     private Przedmioty przedmioty;
     private Uczniowie uczniowie;

    public UczniowiePrzedmioty() {
    }

    public UczniowiePrzedmioty(UczniowiePrzedmiotyId id, Przedmioty przedmioty, Uczniowie uczniowie) {
       this.id = id;
       this.przedmioty = przedmioty;
       this.uczniowie = uczniowie;
    }
   
    public UczniowiePrzedmiotyId getId() {
        return this.id;
    }
    
    public void setId(UczniowiePrzedmiotyId id) {
        this.id = id;
    }
    public Przedmioty getPrzedmioty() {
        return this.przedmioty;
    }
    
    public void setPrzedmioty(Przedmioty przedmioty) {
        this.przedmioty = przedmioty;
    }
    public Uczniowie getUczniowie() {
        return this.uczniowie;
    }
    
    public void setUczniowie(Uczniowie uczniowie) {
        this.uczniowie = uczniowie;
    }




}


